backend:
  name: git-gateway

media_folder: "static/assets"
public_folder: "assets"

collections:
  - name: "verkefni"
    label: "Verkefni"
    folder: "static/verkefni"
    editor:
      preview: false
    create: true
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - { label: "Lýsing", name: "lysing", widget: "text" }
      - { label: "Mynd", name: "featured-img", widget: "image" }
